import type { Metadata } from "next";
import { Volkhov } from "next/font/google";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const DigitalNumbers = localFont({
  src: "./fonts/DigitalNumbers-Regular.ttf",
  variable: "--font-digital-number",
  weight: "100 900",
});
const volkhov = Volkhov({
  subsets: ["latin"],
  weight: ["400", "700", "400", "700"],
  variable: "--font-volkhov",
});

const poppins = Poppins({
  subsets: ["latin-ext"],
  weight: ["100", "200", "300", "400", "500", "600", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${DigitalNumbers.variable} ${volkhov.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
